<template>
  <div class="q-pa-md relative-position" style="height: 280px; max-height: 80vh">
    <q-icon
      v-morph:btn:mygroup:300.resize="morphGroupModel"
      class="absolute-bottom-left q-pb-md"
      fab
      color="info"
      size="md"
      name="fas fa-info-circle"
      @click="nextMorph"
    />
    <!--first step -->
    <q-card
      v-morph:card1:mygroup:500.resize="morphGroupModel"
      class="absolute-bottom-left q-ma-md bg-info text-white"
      style="width: 300px; border-bottom-left-radius: 2em"
    >
      <q-card-section class="text-h6 text-">
        <q-icon name="fas fa-info-circle" class="q-pb-sm" />
        Getting Started
      </q-card-section>

      <q-card-section class="text-subtitle1">
        All assignments will be generated by
        your <span class="text-bold">Head guard</span>.
      </q-card-section>

      <q-card-actions align="right">
        <q-btn flat label="Next" @click="nextMorph" />
      </q-card-actions>
    </q-card>

    <!-- second step -->
    <q-card
      v-morph:card2:mygroup:500.resize="morphGroupModel"
      class="absolute-bottom-left q-ma-md bg-info text-white"
      style="width: 300px; border-bottom-left-radius: 2em"
    >
      <q-card-section class="text-h6">
        <q-icon name="fas fa-info-circle" class="q-pb-sm" />
        Getting Started
      </q-card-section>

      <q-card-section class="text-subtitle1">
        The <span class="text-bold">Assigned Section</span> is where you'll
        recieve new assignments for the day.         
      </q-card-section>

      <q-card-actions align="right">
        <q-btn flat label="Next" @click="nextMorph" />
      </q-card-actions>
    </q-card>  

    <!--third step -->
    <q-card
      v-morph:card3:mygroup:500.resize="morphGroupModel"
      class="absolute-bottom-left q-ma-md bg-info text-white"
      style="width: 320px; border-bottom-left-radius: 2em"
    >
      <q-card-section class="text-h6">
        <q-icon name="fas fa-info-circle" class="q-pb-sm" />
        Getting Started
      </q-card-section>

      <q-card-section class="text-subtitle1">
        The <span class="text-bold">Completed Section</span> is where
        an assignment is fullfilled.
      </q-card-section>

      <q-card-actions align="right">
        <q-btn flat label="Next" @click="nextMorph" />
      </q-card-actions>
    </q-card>

    <!-- last step -->
    <q-card
      v-morph:card4:mygroup:500.tween="morphGroupModel"
      class="absolute-bottom-left q-ma-md bg-info text-white"
      style="width: 320px; border-bottom-left-radius: 2em"
    >
      <q-card-section class="text-h6">
          <q-icon name="fas fa-info-circle" class="q-pb-sm" />
            Guide Finished!
      </q-card-section>

      <q-card-section class="q-py-xl text-center text-subtitle2">
        <p class="text-bold text-body6">Excellent!</p>
        <p>Thank you and patrol safely!</p>
      </q-card-section>

      <q-card-actions align="right">
        <q-btn flat label="Close" @click="nextMorph" />
      </q-card-actions>
    </q-card>

  </div>
</template>

<script>
import { ref } from 'vue'

const nextMorphStep = {
  btn: 'card1',
  card1: 'card2',
  card2: 'card3',
  card3: 'card4',
  card4: 'btn'
}

export default {
  setup () {
    const morphGroupModel = ref('btn')

    return {
      morphGroupModel,
      nextMorph () {
        morphGroupModel.value = nextMorphStep[ morphGroupModel.value ]
      }
    }
  }
}
</script>